### ISSUE TITLE
Can you tell me how to switch to HTTPS and what might be needed

### ISSUE THREAD

**Issue by patagoniahiker** [NWebsec/NWebsec.TestSites#1]
Hello, I am thankful for this nuget nugget :+1:  can you please tell me what I need to include to support HTTPS

do I need to buy my over HTTPS certificate? or can I do without a certificate

**Comment by klings** [comment]
Thank you for the thumbs up!

Yes, you'll need a cert to enable HTTPS. If you have a public website you'd want to obtain a certificate from one of the CA's in the browser trust list.
